import { runSlice } from "./runSlice";
export { store } from "./store";
export type { RootState, AppDispatch } from "./store";
export { useAppDispatch, useAppSelector } from "./hooks";
export { runSlice };
export const setRun = runSlice.actions.setRun;
export const startNewRun = runSlice.actions.startNewRun;
export const addArea = runSlice.actions.addArea;
export const updateArea = runSlice.actions.updateArea;
export const addFogGate = runSlice.actions.addFogGate;
export const setFogGateWarp = runSlice.actions.setFogGateWarp;
export const removeFogGateWarp = runSlice.actions.removeFogGateWarp;
export const setFogGateCleared = runSlice.actions.setFogGateCleared;
export const setKeyAcquired = runSlice.actions.setKeyAcquired;
export const setKeyItemAcquired = runSlice.actions.setKeyItemAcquired;
export const setMajorEventCompleted =
  runSlice.actions.setMajorEventCompleted;
export const setBossDefeated = runSlice.actions.setBossDefeated;
export const setShortcutUnlocked = runSlice.actions.setShortcutUnlocked;
export const setBonfireLit = runSlice.actions.setBonfireLit;
export const clearRun = runSlice.actions.clearRun;
